get nix shell to work finally, but inline-java build fails
after way too long because my laptop sucks, it fails with this message:

INFO: Analyzed 28 targets (76 packages loaded, 4893 targets configured).
INFO: Found 28 targets...
ERROR: /app/inline-java/jni/BUILD.bazel:33:8: Executing genrule //jni:cat-tokens-sh failed: (Exit 127): bash failed: error executing command /nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12/bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12/bin/bash: line 1: $'\r': command not found
ERROR: /app/inline-java/jvm-batching/BUILD.bazel:13:16 HaskellLinkStaticLibrary jvm-batching/libHSjvm-batchingZSjvm-batching.a failed: (Exit 127): bash failed: error executing command /nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12/bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 1289.783s, Critical Path: 0.84s
INFO: 150 processes: 149 internal, 1 linux-sandbox.
FAILED: Build did NOT complete successfully